### ISSUE TITLE
Thin 1.4.1 can not start

### ISSUE THREAD

**Issue by smoothdvd** [macournoyer/thin#115]
I just upgrade to 1.4.1 and met this error:

``` ruby

/usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/backends/tcp_server.rb:16:in `connect': cannot load such file -- thin/connection (LoadError)
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/backends/base.rb:55:in `block in start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/backends/base.rb:63:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/server.rb:159:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/controllers/controller.rb:86:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/runner.rb:185:in `run_command'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/lib/thin/runner.rb:151:in `run!'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/thin-1.4.1/bin/thin:6:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/thin:19:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/thin:19:in `<main>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by vforge** [comment]
:+1:

**Comment by nadirlc** [comment]
adding gem "thin" to the Gemfile worked for me as well. Thanks

**Comment by mooreniemi** [comment]
:+1:

**Comment by sobolevn** [comment]
:+1:

**Comment by danhsh** [comment]
:+1:

**Comment by 23ranjan** [comment]
👍
