### ISSUE TITLE
thin/backends/base.rb:162:in `initialize_connection': can't add a new key into hash during iteration (RuntimeError)

### ISSUE THREAD

**Issue by scanlanjames** [macournoyer/thin#267]
on a sinatra system using thin as the server, this error occaisionally crashes the system, but i can't identifiy a cause.

```
    from /usr/local/rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.3/lib/eventmachine.rb:1469:in `call'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.3/lib/eventmachine.rb:1469:in `event_callback'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
    from /usr/local/rvm/gems/ruby-2.1.3/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.3/bin/thin:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.3/bin/thin:23:in `<main>'
```

**Comment by scanlanjames** [comment]
this is still an issue for me. does it happen for anyone else?

**Comment by macournoyer** [comment]
Seems like a thread related issue...

I'd recommend adding this config to your Sinatra app:

```ruby
set :threaded, false
```

Not sure why they chose to default to `true`, threaded mode is experimental in Thin.
