### ISSUE TITLE
Non ASCII URL causes error on Windows Rails 4.2

### ISSUE THREAD

**Issue by marutosi** [macournoyer/thin#268]
* http://www.redmine.org/issues/19321
* https://bz.apache.org/bugzilla/show_bug.cgi?id=57726
* https://community.bitnami.com/t/problems-with-3-0-1-installation-see-report-inside/30195

On my Japanese Windows 8.1 Pro.

```
Unexpected error while processing request: "\x80" on Windows-31J
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:34:in `file?'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:34:in `block in match?'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:31:in `each'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:31:in `detect'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:31:in `match?'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:107:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/sendfile.rb:
113:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/engine.
rb:518:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/applica
tion.rb:164:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/railtie
.rb:194:in `public_send'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/railtie
.rb:194:in `method_missing'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:86:in `block in pre_process'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:84:in `catch'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:84:in `pre_process'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:53:in `process'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:39:in `receive_data'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmach
ine.rb:187:in `run_machine'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmach
ine.rb:187:in `run'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/backends/bas
e.rb:73:in `start'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/server.rb:16
2:in `start'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/controllers/
controller.rb:87:in `start'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/runner.rb:20
0:in `run_command'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/runner.rb:15
6:in `run!'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/bin/thin:6:in `<top (
required)>'
        c:/Ruby200-x64/bin/thin:23:in `load'
        c:/Ruby200-x64/bin/thin:23:in `<main>'
```

![windows-thin](https://cloud.githubusercontent.com/assets/200784/6846720/c15f5d6e-d403-11e4-8d8a-1636917aae31.png)

**Comment by marutosi** [comment]
* http://www.redmine.org/issues/19374
* https://github.com/rails/rails/issues/19187

```
Unexpected error while processing request: "\x87" followed by "." on Windows-31J

        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:34:in `file?'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:34:in `block in match?'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:31:in `each'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:31:in `detect'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:31:in `match?'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/actionpack-4.2.1/lib/action_disp
atch/middleware/static.rb:107:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rack-1.6.0/lib/rack/sendfile.rb:
113:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/engine.
rb:518:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/applica
tion.rb:164:in `call'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/railtie
.rb:194:in `public_send'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/railties-4.2.1/lib/rails/railtie
.rb:194:in `method_missing'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:86:in `block in pre_process'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:84:in `catch'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:84:in `pre_process'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:53:in `process'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/connection.r
b:39:in `receive_data'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmach
ine.rb:187:in `run_machine'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmach
ine.rb:187:in `run'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/backends/bas
e.rb:73:in `start'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/server.rb:16
2:in `start'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/controllers/
controller.rb:87:in `start'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/runner.rb:20
0:in `run_command'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/lib/thin/runner.rb:15
6:in `run!'
        c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thin-1.6.3/bin/thin:6:in `<top (
required)>'
        c:/Ruby200-x64/bin/thin:23:in `load'
        c:/Ruby200-x64/bin/thin:23:in `<main>'
```
![default](https://cloud.githubusercontent.com/assets/200784/6846884/296fa93a-d405-11e4-9633-6271ccb6c330.png)

**Comment by marutosi** [comment]
Rails 4-2-stable branch includes https://github.com/rails/rails/commit/4df216cb12e35c09ae5ec271755e581d692d0326 .
