### ISSUE TITLE
SSL issue: can't allocate region

### ISSUE THREAD

**Issue by gonchs** [macournoyer/thin#289]
When starting the server on localhost with

```bundle exec thin start --ssl```

the server is unable to process requests, which results in "Internal server error"

```
Using rack adapter
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop
ruby(31701,0x7fff76fae000) malloc: *** mach_vm_map(size=3458764513820545024) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
ruby(31701,0x7fff76fae000) malloc: *** mach_vm_map(size=3458764513820545024) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Unexpected error while processing request: failed to allocate memory
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/em/connection.rb:488:in `get_peer_cert'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/em/connection.rb:488:in `get_peer_cert'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:75:in `pre_process'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:87:in `start'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        /Users/sergey/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        /Users/sergey/.rbenv/versions/2.2.3/bin/thin:23:in `load'
        /Users/sergey/.rbenv/versions/2.2.3/bin/thin:23:in `<main>'
```

**Comment by macournoyer** [comment]
You ran out of memory.

**Comment by gonchs** [comment]
How much memory does it need? This was run in a desktop environment with about 2 GB of free memory left.

**Comment by macournoyer** [comment]
According to the error message `mach_vm_map(size=3458764513820545024)`, Ruby needs to allocate a **huge** amount of memory. Perhaps your app is really big?

**Comment by gonchs** [comment]
The whole app has only 306 LOC

```
+----------------------+-------+-------+---------+---------+-----+-------+
| Name                 | Lines |   LOC | Classes | Methods | M/C | LOC/M |
+----------------------+-------+-------+---------+---------+-----+-------+
| Controllers          |   268 |   210 |       8 |      28 |   3 |     5 |
| Helpers              |     8 |     8 |       0 |       0 |   0 |     0 |
| Models               |    69 |    51 |       3 |       7 |   2 |     5 |
| Mailers              |     0 |     0 |       0 |       0 |   0 |     0 |
| Javascripts          |    61 |    37 |       0 |       5 |   0 |     5 |
| Libraries            |     0 |     0 |       0 |       0 |   0 |     0 |
| Model tests          |    14 |     6 |       2 |       0 |   0 |     0 |
+----------------------+-------+-------+---------+---------+-----+-------+
| Total                |   420 |   312 |      13 |      40 |   3 |     5 |
+----------------------+-------+-------+---------+---------+-----+-------+
  Code LOC: 306     Test LOC: 6     Code to Test Ratio: 1:0.0
```

**Comment by macournoyer** [comment]
That is weird. Perhaps your local cert chain is huge? But even then, couldn't be that used to cause that much memory to be allocated.

Is it possible you tweaked the Ruby GC w/ env variables?

**Comment by x3b3ch3** [comment]
Same issue on qadricore i7 macboopro

**Comment by spikex** [comment]
This is an issue with eventmachine and SSL on El Capitan. Rebuilding with:

```
PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2e/lib/pkgconfig gem install eventmachine
```
(Presumes Brew - tweak the path for whatever version of OpenSSL you have.)

works around whatever the root cause is.

**Comment by x3b3ch3** [comment]
You're right for the problem, but this workaround doesn't fix it.
It still occurs on both of my machines.

**Comment by spikex** [comment]
Maybe try it with a "bundle exec" (if you're using bundler and you haven't), I had a old version somewhere in my path at first. Or maybe an odd interaction with RVM?

**Comment by x3b3ch3** [comment]
I tried this. Thanks.
I had the same issue only once with a recent macbook air.
Both are reinstalled from scratch with same El Capitan Usb boot device, same brew installed packages, same rails, gem, project versions.
Seems hardware is involved with this issue

**Comment by jbosse** [comment]
@x3b3ch3 did you ever resolve this? I am having the same issue. I tried @spikex's workaround with no luck. I even tried `PKG_CONFIG_PATH=/usr/local/Cellar/openssl/1.0.2e/lib/pkgconfig rvm all do gem install eventmachine` in case it was rebuiding the gem in the wrong ruby.
