### ISSUE TITLE
Can't restart thin with kill -HUP ID

### ISSUE THREAD

**Issue by gudata** [macournoyer/thin#291]
I start thin instance

```
bundle exec thin start
```

it runs ok. 

```
Using rack adapter
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
Thin web server (v1.6.1 codename Death Proof)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop
Restarting ...
Waiting for 5 connection(s) to finish, can take up to 30 sec, CTRL+C to stop now
Using rack adapter

Thin web server (v1.6.1 codename Death Proof)

Maximum connections set to 1024

Listening on 0.0.0.0:3000, CTRL+C to stop
```

when I issue

```
kill -HUP NNNNN
```

i got an exception. I have tested with two rails apps.

```
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.

/home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bundler/gems/eventmachine-0de31a845fdb/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)

  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bundler/gems/eventmachine-0de31a845fdb/lib/eventmachine.rb:530:in `start_server'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/backends/tcp_server.rb:16:in `connect'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/backends/base.rb:63:in `block in start'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bundler/gems/eventmachine-0de31a845fdb/lib/eventmachine.rb:194:in `call'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bundler/gems/eventmachine-0de31a845fdb/lib/eventmachine.rb:194:in `run_machine'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bundler/gems/eventmachine-0de31a845fdb/lib/eventmachine.rb:194:in `run'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/backends/base.rb:73:in `start'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/server.rb:162:in `start'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/controllers/controller.rb:87:in `start'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/runner.rb:200:in `run_command'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/lib/thin/runner.rb:156:in `run!'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/gems/thin-1.6.1/bin/thin:6:in `<top (required)>'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bin/thin:23:in `load'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bin/thin:23:in `<main>'
  from /home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bin/ruby_executable_hooks:15:in `eval'
  from home/senior_developer/.rvm/gems/ruby-2.0.0-p481@some_gemset/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by FaheemAlam** [comment]
were you able to fix this? Am having the same issue.

**Comment by 907th** [comment]
I confirm this too
