### ISSUE TITLE
Passing a Fixnum instance as value for header causes error on Thin

### ISSUE THREAD

**Issue by rwillians** [macournoyer/thin#331]
Given the following resource:

```ruby
module MyApp
  module Endpoints
    class Search < Grape::API
      helpers Helpers::Parameters

      resource 'search/people' do
        desc 'Finds people by their registered documents'
        params { use :search_by_documents }
        post do
          people = Models::Profile.matching_any_document(params[:documents])

          header 'X-Results-Count', people.count
          present people, with: Entities::Person::Compact
        end
      end
    end
  end
end
```

Notice I'm passing a response header `header 'X-Results-Count', people.count` where `people.count` returns an instance of `Fixnum`. This response will causes the following error on Thin:

```txt
api_1      | Unexpected error while processing request: undefined method `each' for 1:Fixnum
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/response.rb:74:in `block in headers='
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/utils.rb:501:in `block in each'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/utils.rb:500:in `each'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/rack-1.6.5/lib/rack/utils.rb:500:in `each'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/response.rb:69:in `headers='
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:102:in `post_process'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:194:in `run_machine'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:194:in `run'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:87:in `start'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/bin/thin:22:in `load'
api_1      | 	/opt/sabes_api/vendor/bundle/ruby/2.3.0/bin/thin:22:in `<top (required)>'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
api_1      | 	/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
api_1      | 	/usr/local/bundle/bin/bundle:22:in `load'
api_1      | 	/usr/local/bundle/bin/bundle:22:in `<main>'
```

When I change the header to `header 'X-Results-Count', people.count.to_s` (noticie `people.count` been converted to string) everything working just fine.

As far as I have read Grape's documentation I couldn't seem any reference about header's value should be only strings.

JSYK: I'm using docker image `ruby:2.3.3-slim` and this is my Gemfile:

```ruby
source 'https://rubygems.org'

gem 'grape', '~> 0.19.1'
gem 'grape-entity', '~> 0.6.1'
gem 'mongoid', '~> 6.0.3'
gem 'rack', '~> 1.5'
gem 'rake', '~> 11.3.0'
gem 'sentry-raven', '~> 2.2.0'
gem 'thin', '~> 1.7.0'

group :development, :testing, :staging do
  gem 'activesupport', '~> 5.0.1'
  gem 'json', '~> 2.0.3'
  gem 'rack-test', '~> 0.6.3'
  gem 'rspec', '~> 3.5.0'
  gem 'rubocop', '~> 0.45.0'
  gem 'rubycritic', '~> 3.1.3'
  gem 'simplecov', '~> 0.12.0'
end
```

**Comment by macournoyer** [comment]
Header's value should be string according to the Rack spec: http://www.rubydoc.info/github/rack/rack/master/file/SPEC, which Thin and most servers use.

**Comment by rwillians** [comment]
Oh, okay then.
Thanks for the information.
