### ISSUE TITLE
rspec doesn't run after cloning the repository

### ISSUE THREAD

**Issue by matheussilvasantos** [macournoyer/thin#378]
Hi, I've just cloned the repository to try to run the tests with `bundle exec rspec`, but I'm getting errors:

```bash
An error occurred while loading ./spec/server_spec.rb. - Did you mean?
                    rspec ./spec/server/tcp_spec.rb
                    rspec ./spec/runner_spec.rb
                    rspec ./spec/headers_spec.rb

Failure/Error: require "thin_parser"

LoadError:
  cannot load such file -- thin_parser
# ./lib/thin.rb:39:in `require'
# ./lib/thin.rb:39:in `<top (required)>'
# ./spec/spec_helper.rb:2:in `require'
# ./spec/spec_helper.rb:2:in `<top (required)>'
# ./spec/server_spec.rb:1:in `require'
# ./spec/server_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00006 seconds (files took 0.48454 seconds to load)
0 examples, 0 failures, 30 errors occurred outside of examples
```

How can we run the tests? Is there something missing?

**Comment by Vasfed** [comment]
thin_parser is a native extension, that should be compiled via `rake compile` before rspec.
Or use `rake spec` to run tests (it compiles extension before running)
