### ISSUE TITLE
Support rack 3.0.0

### ISSUE THREAD

**Issue by lucaskanashiro** [macournoyer/thin#389]
[rack version 3.0.0](https://github.com/rack/rack/blob/main/CHANGELOG.md#300---2022-09-06) was released a couple of months ago, it'd be great if thin could also support that.

**Comment by ioquatix** [comment]
Feel free to submit a PR. There is a conformance test suite here: <https://github.com/socketry/rack-conform>. Thin is already supported Rack v2 as you'd probably expect.

**Comment by ioquatix** [comment]
I've tested it with rack-conform (https://github.com/socketry/rack-conform/pull/26), and there is only one issue:

```
2025-03-01 20:17:00 +1300 Unexpected error while processing request: not opened for reading
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/response.rb:12:in 'Thin::Response::Stream#read'
	/Users/samuel/.gem/ruby/3.4.2/gems/protocol-websocket-0.20.1/lib/protocol/websocket/framer.rb:67:in 'Protocol::WebSocket::Framer#read_header'
	/Users/samuel/.gem/ruby/3.4.2/gems/protocol-websocket-0.20.1/lib/protocol/websocket/framer.rb:51:in 'Protocol::WebSocket::Framer#read_frame'
	/Users/samuel/.gem/ruby/3.4.2/gems/protocol-websocket-0.20.1/lib/protocol/websocket/connection.rb:123:in 'Protocol::WebSocket::Connection#read_frame'
	/Users/samuel/.gem/ruby/3.4.2/gems/protocol-websocket-0.20.1/lib/protocol/websocket/connection.rb:295:in 'Protocol::WebSocket::Connection#read'
	/Users/samuel/Developer/socketry/rack-conform/lib/rack/conform/application.rb:103:in 'block in Rack::Conform::Application#test_websocket_echo'
	/Users/samuel/.gem/ruby/3.4.2/gems/async-websocket-0.30.0/lib/async/websocket/adapters/http.rb:41:in 'block in Async::WebSocket::Adapters::HTTP.open'
	/Users/samuel/.gem/ruby/3.4.2/gems/async-http-0.87.0/lib/async/http/body/hijack.rb:39:in 'Async::HTTP::Body::Hijack#call'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/response.rb:144:in 'Method#call'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/response.rb:144:in 'Thin::Response#each'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/connection.rb:118:in 'Thin::Connection#post_process'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/connection.rb:53:in 'Thin::Connection#process'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/connection.rb:39:in 'Thin::Connection#receive_data'
	/Users/samuel/.gem/ruby/3.4.2/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in 'EventMachine.run_machine'
	/Users/samuel/.gem/ruby/3.4.2/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in 'EventMachine.run'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/backends/base.rb:75:in 'Thin::Backends::Base#start'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/server.rb:162:in 'Thin::Server#start'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/controllers/controller.rb:87:in 'Thin::Controllers::Controller#start'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/runner.rb:203:in 'Thin::Runner#run_command'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/lib/thin/runner.rb:159:in 'Thin::Runner#run!'
	/Users/samuel/.gem/ruby/3.4.2/bundler/gems/thin-de6b6188f1f1/bin/thin:6:in '<top (required)>'
	/Users/samuel/.gem/ruby/3.4.2/bin/thin:25:in 'Kernel#load'
	/Users/samuel/.gem/ruby/3.4.2/bin/thin:25:in '<main>'
```

**Comment by womblep** [comment]
@ioquatix Can you please put a version of the latest Thin on Rubygems?
I have tested my production app with Thin master branch, Sinatra 4.1.1, Rack 3.1.12 and everything is working correctly.

**Comment by securecall-dev** [comment]
@ioquatix Please, please please, could we get a release for Thin 2.0 and Rack 3? 
If it helps, I will be willing to do admin work and triage issues.

**Comment by womblep** [comment]
@macournoyer any chance of a new release?

**Comment by ioquatix** [comment]
Okay, I have a little time today, let me take a look.

**Comment by ioquatix** [comment]
Probably the only way to do it is when we have a streaming response, to use a fiber so we can invert the flow control.

**Comment by ioquatix** [comment]
I reviewed the code. It's likely impossible to implement without major changes to the request input buffering. It looks like `thin` never supported `rack.hijack` either.

As such, I'll cut a 2.0 release with this caveat listed. That means `thin` will only have partial support for Rack 3. In essence, it means that it doesn't support Rack 3, but I agree the changes are sufficient to release.

**Comment by womblep** [comment]
@ioquatix thanks. I agree that implementing bidirectional was going to be a big job and not worthwhile. If people want to use websockets they should look at a Rack 3 fully compatible server like Falcon.
I was thinking that changing the error message in the Stream.read might make it more explicit, instead of:
raise ::IOError, 'not opened for reading' if @read_closed
it could just be:
raise ::IOError, 'Stream.read is not implemented and is not supported (thin/issue/389)'
Or something similar. It makes it obvious if someone tries to use it without understanding the background.

**Comment by ioquatix** [comment]
Okay, `v2.0.0` is released. Feel free to submit PRs if you think there are things that can be improved.
